FlagEPCAM = False
cutFlag = False
GerberFolderPath = ''
DialogInput = None
login_username=''
login_password=''
login_user_type=''
FlagTranslatingEP = False
FlagTranslatingG = False
FlagComparingG = False