# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogInput.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(992, 836)
        self.labelJobName = QtWidgets.QLabel(Dialog)
        self.labelJobName.setGeometry(QtCore.QRect(660, 20, 54, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelJobName.setFont(font)
        self.labelJobName.setObjectName("labelJobName")
        self.lineEditJobName = QtWidgets.QLineEdit(Dialog)
        self.lineEditJobName.setGeometry(QtCore.QRect(690, 20, 161, 20))
        self.lineEditJobName.setObjectName("lineEditJobName")
        self.lineEditGerberFolderPath = QtWidgets.QLineEdit(Dialog)
        self.lineEditGerberFolderPath.setGeometry(QtCore.QRect(110, 20, 501, 20))
        self.lineEditGerberFolderPath.setObjectName("lineEditGerberFolderPath")
        self.pushButtonSelectGerber = QtWidgets.QPushButton(Dialog)
        self.pushButtonSelectGerber.setGeometry(QtCore.QRect(20, 20, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonSelectGerber.setFont(font)
        self.pushButtonSelectGerber.setObjectName("pushButtonSelectGerber")
        self.lineEditStep = QtWidgets.QLineEdit(Dialog)
        self.lineEditStep.setGeometry(QtCore.QRect(900, 20, 71, 20))
        self.lineEditStep.setObjectName("lineEditStep")
        self.tableWidgetGerber = QtWidgets.QTableWidget(Dialog)
        self.tableWidgetGerber.setGeometry(QtCore.QRect(10, 80, 971, 621))
        self.tableWidgetGerber.setObjectName("tableWidgetGerber")
        self.tableWidgetGerber.setColumnCount(0)
        self.tableWidgetGerber.setRowCount(0)
        self.pushButtonTranslate = QtWidgets.QPushButton(Dialog)
        self.pushButtonTranslate.setGeometry(QtCore.QRect(110, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonTranslate.setFont(font)
        self.pushButtonTranslate.setObjectName("pushButtonTranslate")
        self.labelStep = QtWidgets.QLabel(Dialog)
        self.labelStep.setGeometry(QtCore.QRect(870, 20, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelStep.setFont(font)
        self.labelStep.setObjectName("labelStep")
        self.pushButtonIdentify = QtWidgets.QPushButton(Dialog)
        self.pushButtonIdentify.setGeometry(QtCore.QRect(20, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonIdentify.setFont(font)
        self.pushButtonIdentify.setObjectName("pushButtonIdentify")
        self.textBrowserLog = QtWidgets.QTextBrowser(Dialog)
        self.textBrowserLog.setGeometry(QtCore.QRect(10, 710, 971, 121))
        self.textBrowserLog.setObjectName("textBrowserLog")
        self.pushButtonOK = QtWidgets.QPushButton(Dialog)
        self.pushButtonOK.setGeometry(QtCore.QRect(320, 50, 75, 23))
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.comboBoxInputMethod = QtWidgets.QComboBox(Dialog)
        self.comboBoxInputMethod.setGeometry(QtCore.QRect(190, 50, 101, 22))
        self.comboBoxInputMethod.setObjectName("comboBoxInputMethod")
        self.comboBoxInputMethod.addItem("")
        self.comboBoxInputMethod.addItem("")
        self.comboBoxInputMethod.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelJobName.setText(_translate("Dialog", "Job:"))
        self.pushButtonSelectGerber.setText(_translate("Dialog", "Path"))
        self.pushButtonTranslate.setText(_translate("Dialog", "Translate"))
        self.labelStep.setText(_translate("Dialog", "Step:"))
        self.pushButtonIdentify.setText(_translate("Dialog", "Identify"))
        self.pushButtonOK.setText(_translate("Dialog", "OK"))
        self.comboBoxInputMethod.setItemText(0, _translate("Dialog", "方案1：悦谱"))
        self.comboBoxInputMethod.setItemText(1, _translate("Dialog", "方案2：G"))
        self.comboBoxInputMethod.setItemText(2, _translate("Dialog", "方案3：待实现"))
