# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogImport.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(486, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(280, 240, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButtonSelectOdb = QtWidgets.QPushButton(Dialog)
        self.pushButtonSelectOdb.setGeometry(QtCore.QRect(10, 10, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonSelectOdb.setFont(font)
        self.pushButtonSelectOdb.setObjectName("pushButtonSelectOdb")
        self.lineEditOdbFolderPath = QtWidgets.QLineEdit(Dialog)
        self.lineEditOdbFolderPath.setGeometry(QtCore.QRect(90, 10, 241, 20))
        self.lineEditOdbFolderPath.setObjectName("lineEditOdbFolderPath")
        self.labelStep = QtWidgets.QLabel(Dialog)
        self.labelStep.setGeometry(QtCore.QRect(340, 70, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelStep.setFont(font)
        self.labelStep.setObjectName("labelStep")
        self.labelJobName = QtWidgets.QLabel(Dialog)
        self.labelJobName.setGeometry(QtCore.QRect(10, 70, 54, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelJobName.setFont(font)
        self.labelJobName.setObjectName("labelJobName")
        self.lineEditJobName = QtWidgets.QLineEdit(Dialog)
        self.lineEditJobName.setGeometry(QtCore.QRect(40, 70, 161, 20))
        self.lineEditJobName.setObjectName("lineEditJobName")
        self.comboBoxStepName = QtWidgets.QComboBox(Dialog)
        self.comboBoxStepName.setGeometry(QtCore.QRect(370, 70, 69, 22))
        self.comboBoxStepName.setObjectName("comboBoxStepName")
        self.labelType = QtWidgets.QLabel(Dialog)
        self.labelType.setGeometry(QtCore.QRect(360, 10, 41, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelType.setFont(font)
        self.labelType.setObjectName("labelType")
        self.comboBoxType = QtWidgets.QComboBox(Dialog)
        self.comboBoxType.setGeometry(QtCore.QRect(390, 10, 69, 22))
        self.comboBoxType.setObjectName("comboBoxType")
        self.comboBoxType.addItem("")
        self.comboBoxType.addItem("")
        self.pushButtonImport = QtWidgets.QPushButton(Dialog)
        self.pushButtonImport.setGeometry(QtCore.QRect(180, 240, 75, 31))
        self.pushButtonImport.setObjectName("pushButtonImport")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonSelectOdb.setText(_translate("Dialog", "Path"))
        self.labelStep.setText(_translate("Dialog", "Step:"))
        self.labelJobName.setText(_translate("Dialog", "Job:"))
        self.labelType.setText(_translate("Dialog", "类型"))
        self.comboBoxType.setItemText(0, _translate("Dialog", "tgz"))
        self.comboBoxType.setItemText(1, _translate("Dialog", "文件夹"))
        self.pushButtonImport.setText(_translate("Dialog", "Import"))
