# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogInputType.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.pushButtonGerber = QtWidgets.QPushButton(Dialog)
        self.pushButtonGerber.setGeometry(QtCore.QRect(20, 70, 151, 111))
        self.pushButtonGerber.setObjectName("pushButtonGerber")
        self.pushButtonOdb = QtWidgets.QPushButton(Dialog)
        self.pushButtonOdb.setGeometry(QtCore.QRect(230, 70, 151, 111))
        self.pushButtonOdb.setObjectName("pushButtonOdb")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonGerber.setText(_translate("Dialog", "Gerber"))
        self.pushButtonOdb.setText(_translate("Dialog", "ODB"))
