# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(366, 195)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(90, 20, 160, 80))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelUserName = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelUserName.setObjectName("labelUserName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelUserName)
        self.lineEditUserName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditUserName.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditUserName)
        self.labelPassword = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPassword.setObjectName("labelPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEditPassword.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditPassword)
        self.pushButtonLogin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(90, 110, 75, 23))
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.checkBoxRememberUserName = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxRememberUserName.setGeometry(QtCore.QRect(180, 110, 71, 20))
        self.checkBoxRememberUserName.setObjectName("checkBoxRememberUserName")
        self.pushButtonSettings = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSettings.setGeometry(QtCore.QRect(290, 110, 75, 23))
        self.pushButtonSettings.setObjectName("pushButtonSettings")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 366, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "悦谱转图比对系统 EPVS-V1.0 登录"))
        self.labelUserName.setText(_translate("MainWindow", "用户名"))
        self.labelPassword.setText(_translate("MainWindow", "密码"))
        self.pushButtonLogin.setText(_translate("MainWindow", "登录"))
        self.checkBoxRememberUserName.setText(_translate("MainWindow", "记住密码"))
        self.pushButtonSettings.setText(_translate("MainWindow", "设置"))
