# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1156, 783)
        self.tabWidgetSettings = QtWidgets.QTabWidget(Dialog)
        self.tabWidgetSettings.setGeometry(QtCore.QRect(0, 0, 1151, 761))
        self.tabWidgetSettings.setObjectName("tabWidgetSettings")
        self.tabCommonSettings = QtWidgets.QWidget()
        self.tabCommonSettings.setObjectName("tabCommonSettings")
        self.groupBoxSettingsG = QtWidgets.QGroupBox(self.tabCommonSettings)
        self.groupBoxSettingsG.setGeometry(QtCore.QRect(10, 290, 531, 221))
        self.groupBoxSettingsG.setObjectName("groupBoxSettingsG")
        self.widget = QtWidgets.QWidget(self.groupBoxSettingsG)
        self.widget.setGeometry(QtCore.QRect(20, 30, 118, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBoxSettingsGSetupType = QtWidgets.QComboBox(self.widget)
        self.comboBoxSettingsGSetupType.setObjectName("comboBoxSettingsGSetupType")
        self.comboBoxSettingsGSetupType.addItem("")
        self.comboBoxSettingsGSetupType.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxSettingsGSetupType)
        self.groupBoxSettingsGeneral = QtWidgets.QGroupBox(self.tabCommonSettings)
        self.groupBoxSettingsGeneral.setGeometry(QtCore.QRect(10, 50, 531, 211))
        self.groupBoxSettingsGeneral.setObjectName("groupBoxSettingsGeneral")
        self.label = QtWidgets.QLabel(self.groupBoxSettingsGeneral)
        self.label.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBoxSettingsGeneral)
        self.lineEdit.setGeometry(QtCore.QRect(100, 30, 341, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBoxSettingsGeneral)
        self.pushButton.setGeometry(QtCore.QRect(450, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButtonSaveSettingsCommon = QtWidgets.QPushButton(self.tabCommonSettings)
        self.pushButtonSaveSettingsCommon.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButtonSaveSettingsCommon.setObjectName("pushButtonSaveSettingsCommon")
        self.tabWidgetSettings.addTab(self.tabCommonSettings, "")
        self.tabAllSettings = QtWidgets.QWidget()
        self.tabAllSettings.setObjectName("tabAllSettings")
        self.pushButtonSaveSettingsAll = QtWidgets.QPushButton(self.tabAllSettings)
        self.pushButtonSaveSettingsAll.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButtonSaveSettingsAll.setObjectName("pushButtonSaveSettingsAll")
        self.treeWidgetSettings = QtWidgets.QTreeWidget(self.tabAllSettings)
        self.treeWidgetSettings.setGeometry(QtCore.QRect(10, 40, 1121, 681))
        self.treeWidgetSettings.setObjectName("treeWidgetSettings")
        self.treeWidgetSettings.headerItem().setText(0, "1")
        self.tabWidgetSettings.addTab(self.tabAllSettings, "")

        self.retranslateUi(Dialog)
        self.tabWidgetSettings.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "配置"))
        self.groupBoxSettingsG.setTitle(_translate("Dialog", "G"))
        self.label_2.setText(_translate("Dialog", "安装类型"))
        self.comboBoxSettingsGSetupType.setItemText(0, _translate("Dialog", "vmware"))
        self.comboBoxSettingsGSetupType.setItemText(1, _translate("Dialog", "local"))
        self.groupBoxSettingsGeneral.setTitle(_translate("Dialog", "通用"))
        self.label.setText(_translate("Dialog", "比对文件夹"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.pushButtonSaveSettingsCommon.setText(_translate("Dialog", "保存修改"))
        self.tabWidgetSettings.setTabText(self.tabWidgetSettings.indexOf(self.tabCommonSettings), _translate("Dialog", "常用设置"))
        self.pushButtonSaveSettingsAll.setText(_translate("Dialog", "保存修改"))
        self.tabWidgetSettings.setTabText(self.tabWidgetSettings.indexOf(self.tabAllSettings), _translate("Dialog", "所有设置"))
