# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1156, 850)
        self.tabWidgetSettings = QtWidgets.QTabWidget(Dialog)
        self.tabWidgetSettings.setGeometry(QtCore.QRect(0, 0, 1151, 841))
        self.tabWidgetSettings.setObjectName("tabWidgetSettings")
        self.tabCommonSettings = QtWidgets.QWidget()
        self.tabCommonSettings.setObjectName("tabCommonSettings")
        self.groupBoxSettingsG = QtWidgets.QGroupBox(self.tabCommonSettings)
        self.groupBoxSettingsG.setGeometry(QtCore.QRect(10, 290, 531, 221))
        self.groupBoxSettingsG.setObjectName("groupBoxSettingsG")
        self.comboBoxSettingsGSetupPath = QtWidgets.QComboBox(self.groupBoxSettingsG)
        self.comboBoxSettingsGSetupPath.setGeometry(QtCore.QRect(70, 100, 101, 20))
        self.comboBoxSettingsGSetupPath.setObjectName("comboBoxSettingsGSetupPath")
        self.comboBoxSettingsGSetupPath.addItem("")
        self.comboBoxSettingsGSetupPath.addItem("")
        self.comboBoxSettingsGSetupPath.addItem("")
        self.labelSettingsCommonGSetupPath = QtWidgets.QLabel(self.groupBoxSettingsG)
        self.labelSettingsCommonGSetupPath.setGeometry(QtCore.QRect(20, 100, 82, 20))
        self.labelSettingsCommonGSetupPath.setObjectName("labelSettingsCommonGSetupPath")
        self.layoutWidget = QtWidgets.QWidget(self.groupBoxSettingsG)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 118, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelSettingsCommonGSetupType = QtWidgets.QLabel(self.layoutWidget)
        self.labelSettingsCommonGSetupType.setObjectName("labelSettingsCommonGSetupType")
        self.horizontalLayout.addWidget(self.labelSettingsCommonGSetupType)
        self.comboBoxSettingsGSetupType = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBoxSettingsGSetupType.setObjectName("comboBoxSettingsGSetupType")
        self.comboBoxSettingsGSetupType.addItem("")
        self.comboBoxSettingsGSetupType.addItem("")
        self.horizontalLayout.addWidget(self.comboBoxSettingsGSetupType)
        self.labelSettingsCommonGUserName = QtWidgets.QLabel(self.groupBoxSettingsG)
        self.labelSettingsCommonGUserName.setGeometry(QtCore.QRect(20, 150, 82, 20))
        self.labelSettingsCommonGUserName.setObjectName("labelSettingsCommonGUserName")
        self.lineEditSettingsCommonGUserName = QtWidgets.QLineEdit(self.groupBoxSettingsG)
        self.lineEditSettingsCommonGUserName.setGeometry(QtCore.QRect(60, 150, 113, 20))
        self.lineEditSettingsCommonGUserName.setObjectName("lineEditSettingsCommonGUserName")
        self.groupBoxSettingsGeneral = QtWidgets.QGroupBox(self.tabCommonSettings)
        self.groupBoxSettingsGeneral.setGeometry(QtCore.QRect(10, 50, 531, 211))
        self.groupBoxSettingsGeneral.setObjectName("groupBoxSettingsGeneral")
        self.label = QtWidgets.QLabel(self.groupBoxSettingsGeneral)
        self.label.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBoxSettingsGeneral)
        self.lineEdit.setGeometry(QtCore.QRect(100, 30, 341, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBoxSettingsGeneral)
        self.pushButton.setGeometry(QtCore.QRect(450, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButtonSaveSettingsCommon = QtWidgets.QPushButton(self.tabCommonSettings)
        self.pushButtonSaveSettingsCommon.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButtonSaveSettingsCommon.setObjectName("pushButtonSaveSettingsCommon")
        self.tabWidgetSettings.addTab(self.tabCommonSettings, "")
        self.tabAllSettings = QtWidgets.QWidget()
        self.tabAllSettings.setObjectName("tabAllSettings")
        self.pushButtonSaveSettingsAll = QtWidgets.QPushButton(self.tabAllSettings)
        self.pushButtonSaveSettingsAll.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButtonSaveSettingsAll.setObjectName("pushButtonSaveSettingsAll")
        self.treeWidgetSettings = QtWidgets.QTreeWidget(self.tabAllSettings)
        self.treeWidgetSettings.setGeometry(QtCore.QRect(10, 40, 1121, 761))
        self.treeWidgetSettings.setObjectName("treeWidgetSettings")
        self.treeWidgetSettings.headerItem().setText(0, "1")
        self.tabWidgetSettings.addTab(self.tabAllSettings, "")
        self.tabDMSDeployment = QtWidgets.QWidget()
        self.tabDMSDeployment.setObjectName("tabDMSDeployment")
        self.tabWidgetSettings.addTab(self.tabDMSDeployment, "")

        self.retranslateUi(Dialog)
        self.tabWidgetSettings.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "配置"))
        self.groupBoxSettingsG.setTitle(_translate("Dialog", "G"))
        self.comboBoxSettingsGSetupPath.setItemText(0, _translate("Dialog", "C:/genesis"))
        self.comboBoxSettingsGSetupPath.setItemText(1, _translate("Dialog", "B:/genesis"))
        self.comboBoxSettingsGSetupPath.setItemText(2, _translate("Dialog", "A:/genesis"))
        self.labelSettingsCommonGSetupPath.setText(_translate("Dialog", "安装路径"))
        self.labelSettingsCommonGSetupType.setText(_translate("Dialog", "安装类型"))
        self.comboBoxSettingsGSetupType.setItemText(0, _translate("Dialog", "vmware"))
        self.comboBoxSettingsGSetupType.setItemText(1, _translate("Dialog", "local"))
        self.labelSettingsCommonGUserName.setText(_translate("Dialog", "用户名"))
        self.groupBoxSettingsGeneral.setTitle(_translate("Dialog", "通用"))
        self.label.setText(_translate("Dialog", "比对文件夹"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.pushButtonSaveSettingsCommon.setText(_translate("Dialog", "保存修改"))
        self.tabWidgetSettings.setTabText(self.tabWidgetSettings.indexOf(self.tabCommonSettings), _translate("Dialog", "常用设置"))
        self.pushButtonSaveSettingsAll.setText(_translate("Dialog", "保存修改"))
        self.tabWidgetSettings.setTabText(self.tabWidgetSettings.indexOf(self.tabAllSettings), _translate("Dialog", "所有设置"))
        self.tabWidgetSettings.setTabText(self.tabWidgetSettings.indexOf(self.tabDMSDeployment), _translate("Dialog", "DMS部署"))

