# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ussd2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 801)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidgetVS = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetVS.setGeometry(QtCore.QRect(10, 160, 841, 581))
        self.tableWidgetVS.setObjectName("tableWidgetVS")
        self.tableWidgetVS.setColumnCount(0)
        self.tableWidgetVS.setRowCount(0)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(860, 160, 221, 581))
        self.textBrowser.setObjectName("textBrowser")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 841, 141))
        self.widget.setObjectName("widget")
        self.horizontalLayoutInput = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayoutInput.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutInput.setObjectName("horizontalLayoutInput")
        self.groupBoxJobA = QtWidgets.QGroupBox(self.widget)
        self.groupBoxJobA.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxJobA.setObjectName("groupBoxJobA")
        self.pushButtonInputA = QtWidgets.QPushButton(self.groupBoxJobA)
        self.pushButtonInputA.setGeometry(QtCore.QRect(80, 30, 161, 71))
        self.pushButtonInputA.setObjectName("pushButtonInputA")
        self.labelJobA = QtWidgets.QLabel(self.groupBoxJobA)
        self.labelJobA.setGeometry(QtCore.QRect(80, 110, 161, 20))
        self.labelJobA.setText("")
        self.labelJobA.setAlignment(QtCore.Qt.AlignCenter)
        self.labelJobA.setObjectName("labelJobA")
        self.horizontalLayoutInput.addWidget(self.groupBoxJobA)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutInput.addItem(spacerItem)
        self.verticalLayoutInput = QtWidgets.QVBoxLayout()
        self.verticalLayoutInput.setObjectName("verticalLayoutInput")
        self.pushButtonVSEP = QtWidgets.QPushButton(self.widget)
        self.pushButtonVSEP.setObjectName("pushButtonVSEP")
        self.verticalLayoutInput.addWidget(self.pushButtonVSEP)
        self.pushButtonVSG = QtWidgets.QPushButton(self.widget)
        self.pushButtonVSG.setObjectName("pushButtonVSG")
        self.verticalLayoutInput.addWidget(self.pushButtonVSG)
        self.verticalLayoutInput.setStretch(0, 1)
        self.verticalLayoutInput.setStretch(1, 1)
        self.horizontalLayoutInput.addLayout(self.verticalLayoutInput)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutInput.addItem(spacerItem1)
        self.groupBoxJobB = QtWidgets.QGroupBox(self.widget)
        self.groupBoxJobB.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxJobB.setObjectName("groupBoxJobB")
        self.pushButtonInputB = QtWidgets.QPushButton(self.groupBoxJobB)
        self.pushButtonInputB.setGeometry(QtCore.QRect(70, 30, 161, 71))
        self.pushButtonInputB.setObjectName("pushButtonInputB")
        self.labelJobB = QtWidgets.QLabel(self.groupBoxJobB)
        self.labelJobB.setGeometry(QtCore.QRect(70, 110, 161, 20))
        self.labelJobB.setText("")
        self.labelJobB.setAlignment(QtCore.Qt.AlignCenter)
        self.labelJobB.setObjectName("labelJobB")
        self.horizontalLayoutInput.addWidget(self.groupBoxJobB)
        self.horizontalLayoutInput.setStretch(0, 4)
        self.horizontalLayoutInput.setStretch(1, 1)
        self.horizontalLayoutInput.setStretch(2, 1)
        self.horizontalLayoutInput.setStretch(3, 1)
        self.horizontalLayoutInput.setStretch(4, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBoxJobA.setTitle(_translate("MainWindow", "料号A"))
        self.pushButtonInputA.setText(_translate("MainWindow", "未加载"))
        self.pushButtonVSEP.setText(_translate("MainWindow", "悦谱比图"))
        self.pushButtonVSG.setText(_translate("MainWindow", "第三方比图"))
        self.groupBoxJobB.setTitle(_translate("MainWindow", "料号B"))
        self.pushButtonInputB.setText(_translate("MainWindow", "未加载"))
