# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ussd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1274, 872)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelSelectGerber = QtWidgets.QLabel(self.centralwidget)
        self.labelSelectGerber.setGeometry(QtCore.QRect(30, 20, 132, 20))
        self.labelSelectGerber.setObjectName("labelSelectGerber")
        self.lineEditGerberFolderPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditGerberFolderPath.setGeometry(QtCore.QRect(180, 20, 461, 20))
        self.lineEditGerberFolderPath.setObjectName("lineEditGerberFolderPath")
        self.pushButtonSelectGerber = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSelectGerber.setGeometry(QtCore.QRect(650, 20, 75, 23))
        self.pushButtonSelectGerber.setObjectName("pushButtonSelectGerber")
        self.tableWidgetGerber = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetGerber.setGeometry(QtCore.QRect(20, 80, 1211, 571))
        self.tableWidgetGerber.setObjectName("tableWidgetGerber")
        self.tableWidgetGerber.setColumnCount(0)
        self.tableWidgetGerber.setRowCount(0)
        self.pushButtonIdentify = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonIdentify.setGeometry(QtCore.QRect(130, 50, 75, 23))
        self.pushButtonIdentify.setObjectName("pushButtonIdentify")
        self.pushButtonTranslateEP = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonTranslateEP.setGeometry(QtCore.QRect(220, 50, 75, 23))
        self.pushButtonTranslateEP.setObjectName("pushButtonTranslateEP")
        self.pushButtonTranslateG = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonTranslateG.setGeometry(QtCore.QRect(320, 50, 75, 23))
        self.pushButtonTranslateG.setObjectName("pushButtonTranslateG")
        self.pushButtonCompareG = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCompareG.setGeometry(QtCore.QRect(510, 50, 75, 23))
        self.pushButtonCompareG.setObjectName("pushButtonCompareG")
        self.pushButtonLoadEPCAM = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoadEPCAM.setGeometry(QtCore.QRect(20, 50, 75, 23))
        self.pushButtonLoadEPCAM.setObjectName("pushButtonLoadEPCAM")
        self.lineEditJobName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditJobName.setGeometry(QtCore.QRect(810, 20, 161, 20))
        self.lineEditJobName.setObjectName("lineEditJobName")
        self.labelJobName = QtWidgets.QLabel(self.centralwidget)
        self.labelJobName.setGeometry(QtCore.QRect(770, 20, 54, 21))
        self.labelJobName.setObjectName("labelJobName")
        self.labelStep = QtWidgets.QLabel(self.centralwidget)
        self.labelStep.setGeometry(QtCore.QRect(990, 20, 31, 21))
        self.labelStep.setObjectName("labelStep")
        self.lineEditStep = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditStep.setGeometry(QtCore.QRect(1020, 20, 71, 20))
        self.lineEditStep.setObjectName("lineEditStep")
        self.textBrowserLog = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowserLog.setGeometry(QtCore.QRect(20, 660, 1211, 192))
        self.textBrowserLog.setObjectName("textBrowserLog")
        self.pushButtonCompareEp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonCompareEp.setGeometry(QtCore.QRect(420, 50, 75, 23))
        self.pushButtonCompareEp.setObjectName("pushButtonCompareEp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1274, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "悦谱转图比对系统 EPVS-V1.0"))
        self.labelSelectGerber.setText(_translate("MainWindow", "请选择原始Gerber文件夹"))
        self.pushButtonSelectGerber.setText(_translate("MainWindow", "选择文件夹"))
        self.pushButtonIdentify.setText(_translate("MainWindow", "Identify"))
        self.pushButtonTranslateEP.setText(_translate("MainWindow", "悦谱转图"))
        self.pushButtonTranslateG.setText(_translate("MainWindow", "第三方转图"))
        self.pushButtonCompareG.setText(_translate("MainWindow", "第三方比图"))
        self.pushButtonLoadEPCAM.setText(_translate("MainWindow", "加载EPCAM"))
        self.labelJobName.setText(_translate("MainWindow", "料号名"))
        self.labelStep.setText(_translate("MainWindow", "Step"))
        self.pushButtonCompareEp.setText(_translate("MainWindow", "悦谱比图"))
